// <auto-generated />
using System;
using GerenTaref.RazorPages.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenTaref.RazorPages.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230625234828_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("GerenTaref.RazorPages.Pages.Model.TarefaModel", b =>
                {
                    b.Property<int?>("TarefaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataFinal")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoTarefa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nota")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsuarioID")
                        .HasColumnType("INTEGER");

                    b.HasKey("TarefaID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Tarefas", (string)null);
                });

            modelBuilder.Entity("GerenTaref.RazorPages.Pages.Model.UsuarioModel", b =>
                {
                    b.Property<int?>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCompleto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioID");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("GerenTaref.RazorPages.Pages.Model.TarefaModel", b =>
                {
                    b.HasOne("GerenTaref.RazorPages.Pages.Model.UsuarioModel", "Responsavel")
                        .WithMany()
                        .HasForeignKey("UsuarioID");

                    b.Navigation("Responsavel");
                });
#pragma warning restore 612, 618
        }
    }
}
